GDNet now uses common from parent directory
prime-slam/glass-detection-dockers pull request #6
Opened 2023-04-02 14:35 UTC by true-real-michael

2023-04-02 14:56 UTC, kirill-ivanov-a requested changes

2023-04-02 14:56 UTC, kirill-ivanov-a commented on detectors/GDNet/Dockerfile
> +COPY ../common common
Parent directory cannot be accessed in docker

2023-04-03 09:34 UTC, kirill-ivanov-a approved these changes

2023-04-03 11:37 UTC, anastasiia-kornilova approved these changes

2023-04-03 11:41 UTC, merged